#!/bin/sh

case "$1" in
    start)
	    python /opt/graphite/bin/carbon-cache.py start
        ;;
    stop)
        ps aux | grep carbon-cache | grep -v grep | awk '{print $2}' | xargs kill
        ;;
    *)
        echo "Usage: carbon {start|stop}" >&2
        exit 3
        ;;
esac